name: Synchronize Pull Request

on:
  pull_request:
    types: [ synchronize ]

jobs:
  access_cloudfront:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials from my account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/github-cloudfront-test
          aws-region: ap-northeast-1
      - name: Get CloudFront ARN
        id: arn
        run: |
          echo "ARN=$(aws resourcegroupstaggingapi get-resources --tag-filters Key=for_nannany,Values=vacant --max-items 1 --region us-east-1  | jq -r ".ResourceTagMappingList[].ResourceARN")" >>$GITHUB_OUTPUT
      - name: Describe CloudFront
        id: describe
        run: |
          aws cloudfront get-distribution-config --id $ID | jq -r '.DistributionConfig.Origins.Items[].DomainName | select(. | test(".*s3\\.ap-northeast-1\\.amazonaws\\.com"))'
        env:
          ID: $(echo ${{ steps.arn.outputs.ARN }} | sed 's:.*/::')
      - name: Update CloudFront tag
        id: update
        run: |
          aws cloudfront tag-resource --resource ${{ steps.arn.outputs.ARN }} --tags 'Items=[{Key=for_nannany,Value=${{ github.head_ref }}}]'
